openapi: 3.0.3
info:
  title: Vite SpecKit Posts API
  description: API contract for posts management using JSONPlaceholder
  version: 1.0.0
servers:
  - url: https://jsonplaceholder.typicode.com
    description: JSONPlaceholder API (mock server)

paths:
  /posts:
    get:
      operationId: getPosts
      summary: Get all posts
      description: Retrieves a paginated list of posts sorted by ID descending (newest first)
      parameters:
        - name: _page
          in: query
          description: Page number (1-indexed)
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: _limit
          in: query
          description: Number of items per page
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: _sort
          in: query
          description: Field to sort by
          required: false
          schema:
            type: string
            default: id
        - name: _order
          in: query
          description: Sort order
          required: false
          schema:
            type: string
            enum: [asc, desc]
            default: desc
      responses:
        "200":
          description: Successful response
          headers:
            x-total-count:
              description: Total number of posts
              schema:
                type: integer
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Post"
    post:
      operationId: createPost
      summary: Create a new post
      description: Creates a new post (mock - returns fake ID)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostCreateRequest"
      responses:
        "201":
          description: Post created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"

  /posts/{id}:
    get:
      operationId: getPostById
      summary: Get a post by ID
      description: Retrieves a single post by its ID
      parameters:
        - name: id
          in: path
          required: true
          description: Post ID
          schema:
            type: integer
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"
        "404":
          description: Post not found
    put:
      operationId: updatePost
      summary: Update a post
      description: Updates an existing post (mock - returns updated data)
      parameters:
        - name: id
          in: path
          required: true
          description: Post ID
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostUpdateRequest"
      responses:
        "200":
          description: Post updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"
        "404":
          description: Post not found
    delete:
      operationId: deletePost
      summary: Delete a post
      description: Deletes a post (mock - returns empty object)
      parameters:
        - name: id
          in: path
          required: true
          description: Post ID
          schema:
            type: integer
      responses:
        "200":
          description: Post deleted successfully
          content:
            application/json:
              schema:
                type: object
        "404":
          description: Post not found

components:
  schemas:
    Post:
      type: object
      required:
        - id
        - userId
        - title
        - body
      properties:
        id:
          type: integer
          description: Unique identifier
          example: 1
        userId:
          type: integer
          description: User ID who created the post
          example: 1
        title:
          type: string
          description: Post title
          minLength: 1
          maxLength: 200
          example: "sunt aut facere repellat provident"
        body:
          type: string
          description: Post content
          minLength: 1
          maxLength: 10000
          example: "quia et suscipit\nsuscipit recusandae..."

    PostCreateRequest:
      type: object
      required:
        - userId
        - title
        - body
      properties:
        userId:
          type: integer
          description: User ID (default 1 for this app)
          example: 1
        title:
          type: string
          description: Post title (trimmed)
          minLength: 1
          maxLength: 200
        body:
          type: string
          description: Post content (trimmed)
          minLength: 1
          maxLength: 10000

    PostUpdateRequest:
      type: object
      required:
        - id
        - userId
        - title
        - body
      properties:
        id:
          type: integer
          description: Post ID
        userId:
          type: integer
          description: User ID
        title:
          type: string
          description: Post title (trimmed)
          minLength: 1
          maxLength: 200
        body:
          type: string
          description: Post content (trimmed)
          minLength: 1
          maxLength: 10000

    PaginatedResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/Post"
        total:
          type: integer
          description: Total number of items
        page:
          type: integer
          description: Current page number
        pageSize:
          type: integer
          description: Items per page
